package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF9619C6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF320046)
val md_theme_light_secondary = Color(0xFF705479)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF9D8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF291232)
val md_theme_light_tertiary = Color(0xFF944745)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onTertiaryContainer = Color(0xFF3D0508)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEBDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF332F33)
val md_theme_light_inverseOnSurface = Color(0xFFF7EFF3)
val md_theme_light_inversePrimary = Color(0xFFECB1FF)

val md_theme_dark_primary = Color(0xFFECB1FF)
val md_theme_dark_onPrimary = Color(0xFF520070)
val md_theme_dark_primaryContainer = Color(0xFF75009E)
val md_theme_dark_onPrimaryContainer = Color(0xFFF9D8FF)
val md_theme_dark_secondary = Color(0xFFDDBBE5)
val md_theme_dark_onSecondary = Color(0xFF402748)
val md_theme_dark_secondaryContainer = Color(0xFF573D60)
val md_theme_dark_onSecondaryContainer = Color(0xFFF9D8FF)
val md_theme_dark_tertiary = Color(0xFFFFB3AF)
val md_theme_dark_onTertiary = Color(0xFF5A1A1B)
val md_theme_dark_tertiaryContainer = Color(0xFF77302F)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1E1B1E)
val md_theme_dark_onBackground = Color(0xFFE8E0E5)
val md_theme_dark_surface = Color(0xFF1E1B1E)
val md_theme_dark_onSurface = Color(0xFFE8E0E5)
val md_theme_dark_surfaceVariant = Color(0xFF4C444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CD)
val md_theme_dark_outline = Color(0xFF988E97)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE8E0E5)
val md_theme_dark_inverseOnSurface = Color(0xFF332F33)
val md_theme_dark_inversePrimary = Color(0xFF9619C6)


val seed = Color(0xFF8D01BD)
